apiVersion: apps/v1
kind: Deployment                                          # 1
metadata:
  name: sa-frontend
  labels:
    app: sa-frontend
spec:
  selector:
    matchLabels:
      app: sa-frontend
  replicas: 2                                             # 2
  minReadySeconds: 15
  strategy:
    type: Recreate                                   # 3                                      # 5
  template:
    metadata:
      labels:
        app: sa-frontend                                  # 6
    spec:
      containers:
        - image: liangrrr/sentiment-analysis-frontend:cnmb
          imagePullPolicy: Always                         # 7
          name: sa-frontend
          env:
            - name: REACT_APP_WEBAPP_URL
              value: "http://sa-web-app"
          ports:
            - containerPort: 3000
